# server配置
server:
  port: 8080
  servlet:
    context-path: /

# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:sqlserver://localhost:1433;DatabaseName=sm_db;encrypt=false;sendStringParametersAsUnicode=true;characterEncoding=UTF-8;useUnicode=true;charset=UTF-8
      username: rick
      password: rick
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.atguigu.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted  #全局逻辑删除
      id-type: auto #主键策略自增长
      table-prefix: news_ # 设置表的前缀

#jwt配置
jwt:
  token:
    tokenExpiration: 120 #有效时间,单位分钟
    tokenSignKey: headline123456  #当前程序签名秘钥 自定义